/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.pulsar.client.impl.conf.ClientConfigurationData;
import org.apache.pulsar.client.impl.conf.ConfigurationDataUtils;

import java.util.Map;

public class App {
    public static void main(String[] args) {
        Map<String, Object> incorrectConfig = Map.of("konnektionTimeoutMs", 11111);

        try {
            ClientConfigurationData conf = ConfigurationDataUtils.loadData(incorrectConfig, new ClientConfigurationData(), ClientConfigurationData.class);
            System.out.println("No exception was thrown");
        } catch (RuntimeException e) {
            System.out.println("Runtime exception was thrown");
            throw new RuntimeException(e);
        }
    }
}
